# Generated by Django 3.0.6 on 2020-06-20 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop_entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_number', models.CharField(blank=True, max_length=20)),
                ('entry_date', models.DateField()),
                ('customer_name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('device_name', models.CharField(choices=[('dell', 'Dell'), ('hp', 'HP'), ('acer', 'Acer'), ('toshiba', 'Toshiba'), ('asus', 'ASUS'), ('gigabyte', 'Giga Byte'), ('fujitsu', 'Fujitsu'), ('mac', 'Macbook'), ('samsung', 'Samsung'), ('emachine', 'emachine'), ('other', 'Other')], max_length=50)),
                ('device_detail', models.CharField(max_length=150)),
                ('problem', models.CharField(max_length=50)),
                ('solution', models.CharField(choices=[('ok', 'Ok'), ('return', 'Return')], max_length=50)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('ongoing', 'Ongoing'), ('waiting', 'Waiting'), ('dispatched', 'Dispatched')], max_length=50)),
                ('remarks', models.CharField(max_length=50)),
            ],
        ),
    ]
