# Generated by Django 3.0.6 on 2020-06-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrybook', '0005_auto_20200620_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop_entry',
            name='address',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='laptop_entry',
            name='contact',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='laptop_entry',
            name='device_name',
            field=models.CharField(blank=True, choices=[('dell', 'Dell'), ('hp', 'HP'), ('acer', 'Acer'), ('toshiba', 'Toshiba'), ('asus', 'ASUS'), ('gigabyte', 'Giga Byte'), ('fujitsu', 'Fujitsu'), ('mac', 'Macbook'), ('samsung', 'Samsung'), ('emachine', 'emachine'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='laptop_entry',
            name='remarks',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='laptop_entry',
            name='solution',
            field=models.CharField(blank=True, choices=[('ok', 'Ok'), ('return', 'Return')], max_length=50),
        ),
        migrations.AlterField(
            model_name='laptop_entry',
            name='status',
            field=models.CharField(blank=True, choices=[('completed', 'Completed'), ('ongoing', 'Ongoing'), ('waiting', 'Waiting'), ('dispatched', 'Dispatched')], max_length=50),
        ),
    ]
