# Generated by Django 3.0.6 on 2020-06-22 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrybook', '0006_auto_20200621_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desktop_entry',
            name='entry_date',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
