# Generated by Django 3.0.6 on 2020-06-22 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrybook', '0007_auto_20200622_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop_entry',
            name='entry_date',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='entry_date',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
