# Generated by Django 3.0.6 on 2020-06-27 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrybook', '0008_auto_20200622_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop_entry',
            name='technician',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
