# Generated by Django 3.0.6 on 2020-06-27 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrybook', '0009_laptop_entry_technician'),
    ]

    operations = [
        migrations.AddField(
            model_name='desktop_entry',
            name='technician',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='recovery',
            name='technician',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
