# Generated by Django 3.0.6 on 2020-06-28 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrybook', '0011_auto_20200627_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_number', models.CharField(blank=True, max_length=20)),
                ('entry_date', models.CharField(blank=True, max_length=20)),
                ('customer_name', models.CharField(max_length=50)),
                ('contact', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=50)),
                ('inquery_detail', models.CharField(max_length=1000)),
                ('source', models.CharField(blank=True, choices=[('facebook', 'Facebook'), ('google', 'Google'), ('friend', 'Friend'), ('youtube', 'Youtube'), ('marketing', 'Marketing/Ads')], max_length=50)),
                ('remarks', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
