# Generated by Django 3.0.6 on 2020-06-29 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrybook', '0013_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='category',
            new_name='order_details',
        ),
        migrations.AddField(
            model_name='orders',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='item',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='orders',
            name='quantity',
            field=models.IntegerField(blank=True),
        ),
    ]
