# Generated by Django 3.0.6 on 2020-06-29 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrybook', '0014_auto_20200629_0850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='item',
            new_name='order_detail',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='order_details',
        ),
    ]
