# Generated by Django 3.0.6 on 2020-06-22 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquery', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Laptop_entry',
            new_name='inquery',
        ),
    ]
